apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-server
  labels:
    run: mlflow-model-server
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    run: mlflow-model-server