apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-server
  labels:
    run: mlflow-model-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: mlflow-model-server