apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-operator
  labels:
    run: mlflow-model-operator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: mlflow-model-operator
