# Multiple roles: one per each deployed component
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-server-deployer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["mlflow-model-server"]
  verbs: ["patch", "get", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["mlflow-model-server"]
  verbs: ["patch", "get", "delete", "create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create"]
- apiGroups: ["", "deployments", "replicasets", "apps"]
  resources: ["services", "deployments.apps", "deployments", "replicasets.apps", "pods"]
  verbs: ["list"]
---
# Multiple role bindings: one per each role above
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-server-deployer
subjects:
- kind: ServiceAccount
  name: mlflow-model-operator
roleRef:
  kind: Role
  name: model-server-deployer
  apiGroup: ""
