apiVersion: v1
kind: Service
metadata:
  name: mlflow-seldon-synchronizer
  labels:
    run: mlflow-seldon-synchronizer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: mlflow-seldon-synchronizer
